/**
 * MIT License
 * Copyright (c) 2017 André Reis
 *
 * Created on: Sep 18, 2017
 *     Author: André Reis <andre.lgr@gmail.com>
 */

#ifndef INCLUDE_DEVICE_TEMPERATURE_SENSOR_TEMPERATURE_SENSOR_TYPES_H
#define INCLUDE_DEVICE_TEMPERATURE_SENSOR_TEMPERATURE_SENSOR_TYPES_H

typedef enum {
  TEMPERATURE_SENSOR_ID_INVALID = 0,
  TEMPERATURE_SENSOR_ID_NONE,
  TEMPERATURE_SENSOR_ID_COLECTOR,
  TEMPERATURE_SENSOR_ID_POOL,
  TEMPERATURE_SENSOR_ID_MAX
} temperature_sensor_id_t;

#endif  // INCLUDE_DEVICE_TEMPERATURE_SENSOR_TEMPERATURE_SENSOR_TYPES_H
